services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - medic-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Alembic migration 파일 자동 동기화
      - ./alembic/versions:/app/alembic/versions
    networks:
      - medic-network

networks:
  medic-network:
    driver: bridge