version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/medic_db
      - ML_SERVICE_URL=http://ml:8001
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - ml
      - redis
    networks:
      - medic-network

  ml:
    build:
      context: .
      dockerfile: Dockerfile.ml
    ports:
      - "8001:8001"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - MODEL_PATH=/ml/models
      - REDIS_URL=redis://redis:6379
    volumes:
      - ml-models:/ml/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - medic-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=medic_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - medic-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - medic-network

volumes:
  postgres-data:
  redis-data:
  ml-models:

networks:
  medic-network:
    driver: bridge
