"""add_current_session_start_message_id_to_chat_rooms

Revision ID: 3d1a0d562ec4
Revises: 193fb76cc51c
Create Date: 2025-09-29 18:34:41.299253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d1a0d562ec4'
down_revision: Union[str, Sequence[str], None] = '193fb76cc51c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('current_session_start_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'current_session_start_message_id')
    # ### end Alembic commands ###
