"""Initial migration with current schema

Revision ID: 4703eec81e3b
Revises:
Create Date: 2025-09-03 06:53:53.724879

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4703eec81e3b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_rooms", sa.Column("final_disease_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_chat_rooms_final_disease_id"),
        "chat_rooms",
        ["final_disease_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "chat_rooms",
        "diseases",
        ["final_disease_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("departments_code_key", "departments", type_="unique")
    op.drop_column("departments", "description")
    op.drop_column("departments", "code")
    op.alter_column(
        "hospital_recommendations", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "hospital_recommendations", "rank", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "hospital_recommendations", "rank", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "hospital_recommendations", "user_id", existing_type=sa.UUID(), nullable=True
    )
    op.add_column(
        "departments",
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "departments",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint("departments_code_key", "departments", ["code"])
    op.drop_constraint(None, "chat_rooms", type_="foreignkey")
    op.drop_index(op.f("ix_chat_rooms_final_disease_id"), table_name="chat_rooms")
    op.drop_column("chat_rooms", "final_disease_id")
    # ### end Alembic commands ###
