"""Add code fields to equipment models

Revision ID: 6c338738022f
Revises: 24c06c16c05a
Create Date: 2025-09-03 08:21:10.724127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c338738022f'
down_revision: Union[str, Sequence[str], None] = '24c06c16c05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital_equipment', sa.Column('model_name', sa.String(), nullable=True))
    op.add_column('hospital_equipment', sa.Column('license_number', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('encrypted_code', sa.String(), nullable=False))
    op.add_column('hospitals', sa.Column('hospital_type_code', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('hospital_type_name', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('region_code', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('region_name', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('district_code', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('district_name', sa.String(), nullable=True))
    op.add_column('hospitals', sa.Column('postal_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'hospitals', ['encrypted_code'])
    op.drop_column('hospitals', 'operating_hours')
    op.drop_column('hospitals', 'type')
    op.drop_column('hospitals', 'department')
    op.add_column('medical_equipment_categories', sa.Column('code', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'medical_equipment_categories', ['code'])
    op.drop_column('medical_equipment_categories', 'description')
    op.add_column('medical_equipment_subcategories', sa.Column('code', sa.String(), nullable=False))
    op.drop_column('medical_equipment_subcategories', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_equipment_subcategories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('medical_equipment_subcategories', 'code')
    op.add_column('medical_equipment_categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'medical_equipment_categories', type_='unique')
    op.drop_column('medical_equipment_categories', 'code')
    op.add_column('hospitals', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hospitals', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hospitals', sa.Column('operating_hours', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.drop_column('hospitals', 'postal_code')
    op.drop_column('hospitals', 'district_name')
    op.drop_column('hospitals', 'district_code')
    op.drop_column('hospitals', 'region_name')
    op.drop_column('hospitals', 'region_code')
    op.drop_column('hospitals', 'hospital_type_name')
    op.drop_column('hospitals', 'hospital_type_code')
    op.drop_column('hospitals', 'encrypted_code')
    op.drop_column('hospital_equipment', 'license_number')
    op.drop_column('hospital_equipment', 'model_name')
    # ### end Alembic commands ###
