"""fix_hospital_recommendations_id_autoincrement

Revision ID: b8250c1da520
Revises: bca54479b0e0
Create Date: 2025-09-04 12:37:44.095439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8250c1da520'
down_revision: Union[str, Sequence[str], None] = 'bca54479b0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
